#!/bin/sh

# Copyright 2004-2007 Joyent Inc.
# 
# Redistribution and/or modification of this code is governed
# by either the GPLv2 or Joyent Commercial Software licenses.
# 
# Report issues and contribute at http://dev.joyent.com/
# 
# $Id$

# mongrel startup script, Solaris 11

cd /opt/joyent/connector/current
case "$1" in
	start)
	;;
	stop)
	pkill searchserver
	/opt/csw/bin/mongrel_rails cluster::stop
	;;
	restart)
	pkill searchserver # this may not work on solaris?
	/opt/csw/bin/mongrel_rails cluster::stop
	/opt/csw/bin/ruby script/searchserver
	/opt/csw/bin/mongrel_rails cluster::start
	;;
	*)
	echo "Usage: $0 {start | stop | restart}"
	;;
esac

exit 0