#!/usr/bin/env ruby
# ++
# Copyright 2004-2007 Joyent Inc.
# 
# Redistribution and/or modification of this code is 
# governed by the GPLv2.
# 
# Report issues and contribute at http://dev.joyent.com/
# 
# $Id$
# --

unless ARGV.size == 1
  puts "usage: ./activate <organization_domain>"
  exit
end                                                       
           
require File.dirname(__FILE__) + '/../config/boot'  
require "#{RAILS_ROOT}/config/environment"
          
def log(message)
  puts message  
end     

log "Loading #{RAILS_ENV} environment.\n"
organizations = []

if ARGV[0] == '*'
  organizations = Organization.find(:all)
else
  domain        = Domain.find_by_email_domain(ARGV[0])
  organizations = [domain.organization] if domain
end       

organizations.each do |org|
  log "\nActivating #{org.name} (#{org.system_domain.email_domain})."
  org.activate!
end