#!/usr/bin/env ruby
# ++
# Copyright 2004-2007 Joyent Inc.
# 
# Redistribution and/or modification of this code is 
# governed by the GPLv2.
# 
# Report issues and contribute at http://dev.joyent.com/
# 
# $Id$
# --

unless ARGV.size == 1
  puts "usage: ./organization_id <organization_domain>"
  exit
end                                                       
           
require File.dirname(__FILE__) + '/../config/boot'  
require "#{RAILS_ROOT}/config/environment"
          
domain = Domain.find_by_email_domain(ARGV[0])
puts domain.organization.id if domain
