#!/usr/bin/env ruby
# ++
# Copyright 2004-2007 Joyent Inc.
# 
# Redistribution and/or modification of this code is 
# governed by the GPLv2.
# 
# Report issues and contribute at http://dev.joyent.com/
# 
# $Id$
# --

ENV['RAILS_ENV'] ||= 'production'

require File.dirname(__FILE__) + '/../config/environment'
fork and exit
AsyncSearchServer.new("http://#{JoyentConfig.search_host}:#{JoyentConfig.search_port}/node/connector", JoyentConfig.search_user, JoyentConfig.search_password).do_work